### ISSUE TITLE
Input not scaling on mobile devices

### ISSUE THREAD

**Issue by nathanbiehl** [ajimix/Input-Framer#19] opened 2017-07-31 14:30 UTC
Noticing some scaling issues on mobile device browsers with this input. Easy to reproduce with Chrome inspect's device toolbar or by setting a mobile user agent in Safari. 

**Desktop:**
<img width="450" alt="screen shot 2017-07-31 at 9 23 59 am" src="https://user-images.githubusercontent.com/4493225/28782219-27115e6a-75d2-11e7-8d1c-d37efac66a53.png">

**Mobile:**
<img width="450" alt="screen shot 2017-07-31 at 9 24 32 am" src="https://user-images.githubusercontent.com/4493225/28782220-271359d6-75d2-11e7-932a-311044f81965.png">

**Comment by ajimix** [comment] 2017-08-01 00:42
Hey @nathanbiehl I think #18 fixes this issue. I'm waiting to see if @ofhouse can confirm that his code is ok to merge before merging it as I'm currently outside of my office for some days and I cannot test it currently.
If he doesn't answer I'll test the code and merge it in a few days and come back to this issue with the solution :)

**Comment by melisamasso** [comment] 2017-08-02 13:56
Having the same problem. Has anyone found a fix?

**Comment by ajimix** [comment] 2017-08-03 00:11
Hey @melisamasso as I said before, this will be fixed soon once we merge #18 which will be hopefully this week :)

**Comment by ajimix** [comment] 2017-08-09 00:53
The code is merged now so if you download latest version 1.7.0 you should be able to have it properly resized.
Please reopen the issue if the problem persists.
Thanks :)

**Comment by nathanbiehl** [comment] 2017-08-10 04:16
@ajimix unfortunately I'm still seeing the scaling issue after updating my coffee script file. The input appears to still be scaled at its original 1x px size, while the rest of the UI is scaled up to 2x.

<img width="422" alt="screen shot 2017-08-09 at 11 15 11 pm" src="https://user-images.githubusercontent.com/4493225/29154236-a90ea43a-7d58-11e7-95b3-e442b24c9ecb.png">


Able to reproduce by using chrome -> inspect -> toggle device toolbar & select 'iphone 6'.

**Comment by ajimix** [comment] 2017-08-10 06:09
Ok I'll reopen the issue then, and I'll check it once I'm back home in a few days. Meanwhile if someone can check it and make a pull request it would be nice :)

**Comment by ofhouse** [comment] 2017-08-10 10:33
@nathanbiehl Can you provide a minimal example project to reproduce the issue?
Asking because I've tested it [here](https://github.com/ajimix/Input-Framer/pull/18#issuecomment-320934807) with other results, so it would be great to see whats happening in your code.

**Comment by nathanbiehl** [comment] 2017-08-10 14:22
I'm working on simplifying my prototype. After stripping properties from one of the inputs,  one of them is now resizing. I'll hopefully be able to isolate some of problematic properties.

**Comment by nathanbiehl** [comment] 2017-08-10 15:22
@ofhouse 

Looks like the issue is with setting the height and width through css style properties. Styles are the only way I can change the color of the inputed text. Setting color through the component 'color' option does nothing. While I was setting color I was also using style to set sizing. That works at 1x in a desktop browser, but when the layout displays on a mobile devices it doesn't get scaled. 

```
new_password_input_hidden.style = 
	color: "#1F6196"
	fontSize: "16px"
	width: "290px"
	height: "44px"
```

Here's a simple demo. Top input has height & width set in options, bottom input has them set in styles: https://framer.cloud/QyGMO

**Comment by ajimix** [comment] 2017-08-10 15:26
Hey @nathanbiehl starting from the latest version released a few hours ago, you can use the textColor property. 
For the width and height, you should use the properties and not setting the style manually like you are doing. 
Please try using the properties and let's see if it works :)

**Comment by nathanbiehl** [comment] 2017-08-10 17:41
Can't fully convert to the textColor option. It does set the color on creation, but I have to still use the style property to change the text color in real time (e.g. changing an input's text to an error color).

**Comment by ajimix** [comment] 2017-08-10 23:43
Ok you can use the style then, but only for the color. Don't use the other properties as those are the ones making your input fail when retina

**Comment by ajimix** [comment] 2017-08-16 04:54
I'm closing the issue as looks like it was a problem with the code.
Please reopen if necessary.

**Closed as completed by ajimix** 2017-08-16 04:54 UTC
