### ISSUE TITLE
Delay in showing text first time

### ISSUE THREAD

**Issue by l-ollie** [ajimix/Input-Framer#27] opened 2017-11-08 09:30 UTC
There is a delay in showing the texts when you focus on the text field the first time. I start to type and I need to deselect the text field in order to show the typed text. This is only the case after I restart the prototype and start typing the first time. 

When I type and deselect the text field, it shows the typed text after a short while. This is quit confusing since there is no visual feedback for using this text field (only the first time after restarting prototype).

**Comment by ajimix** [comment] 2017-11-08 12:33
Hello @l-ollie can you please share a simple prototype where this is happening? I just made a quick test and everything is super fast for me on Desktop and on the iPhone.

This is the project where I tested it 
[Test.framer.zip](https://github.com/ajimix/Input-Framer/files/1453834/Test.framer.zip)

**Comment by l-ollie** [comment] 2017-11-09 10:16
Hello Ajimix,

I have the same with your Test.framer. 
I have recorded my behaviour with framer. I'll send you the movie.

The problem is: Lets say i have a password textfield.  I type  "1234"  in the text field. The text field does not show that i have typed something, or that i have selected it. Only if move the mouse away from the prototype, it show that i have typed something.  

I hope this make it more clear what my problem is.

[The link to the movie.
](https://drive.google.com/open?id=1apWePXrxOLUvibAHcju4H7FvIQNzk_KM)

p.s. I don't think this should matter much, but I use a Mac mini (Late 2014).

Greetz!

**Comment by ajimix** [comment] 2017-11-09 11:09
Ok I was able to reproduce the issue. It looks like there is some problem with inputs with transparent background in the latest version of Framer. Can you please try now with the updated module? https://raw.githubusercontent.com/ajimix/Input-Framer/master/input.coffee

I'm closing the issue. Please reopen if the problem persists, but on my tests, the problem is gone.

**Closed as completed by ajimix** 2017-11-09 11:09 UTC

**Comment by l-ollie** [comment] 2017-11-14 13:48
Yes, it look good! 
Thank you :)
